### ISSUE TITLE
cc_hmacStringUsingAlg 和cc_hmacDataUsingAlg方法计算结果不一致

### ISSUE THREAD

**Issue by YuriHong** [lgc107/CommonCrypto#1]
方法cc_hmacStringUsingAlg 中：CCHmac(alg, keyData.bytes, strlen(keyData.bytes), self.bytes, self.length, result);
参数有误，应修改为：
CCHmac(alg, keyData.bytes, keyData.length, self.bytes, self.length, result);

**Comment by lgc107** [comment]
如果用UTF8编码转换为String，确实会有问题，对二进制数据做一下处理就好了，之前是看二进制一样就没注意 ，commit:
343d97e
